let pattern, selectedFile;
const $=id=>document.getElementById(id), status=$("status"), file=$("file"), button=$("convert"), format=$("format");
const conversionBase=741, conversionKey="xtranscoder-conversion-count";
function conversionTotal(){try{const value=Number(localStorage.getItem(conversionKey));return Number.isSafeInteger(value)&&value>=conversionBase?value:conversionBase}catch{return conversionBase}}
function renderConversionCount(animate=false){const el=$("conversion-count");if(!el)return;const total=conversionTotal();if(!animate){el.textContent=total.toLocaleString();return}const start=Math.max(conversionBase,total-1),started=performance.now(),duration=420;function tick(now){const progress=Math.min((now-started)/duration,1),value=Math.round(start+(total-start)*progress);el.textContent=value.toLocaleString();if(progress<1)requestAnimationFrame(tick);else el.animate([{transform:"scale(1)"},{transform:"scale(1.12)",color:"#b8fff5"},{transform:"scale(1)"}],{duration:360,easing:"ease-out"})}requestAnimationFrame(tick)}
function recordConversion(){try{localStorage.setItem(conversionKey,String(conversionTotal()+1))}catch{}renderConversionCount(true)}
renderConversionCount();
const num=/[-+]?(?:\d+(?:\.\d*)?|\.\d+)(?:[Ee][-+]?\d+)?/g;
const numbers=s=>(s.match(num)||[]).map(Number);
function pairs(text,skip=0){const p=text.split(/\r?\n/).slice(skip).map(l=>numbers(l)).filter(a=>a.length>=2).map(a=>[a[0],a[1]]);if(!p.length)throw Error("No two-column diffraction data was found.");return p}
function type(name,text,bytes){const h=text.slice(0,4096).trimStart();if(bytes[0]===70&&bytes[1]===73)return"2.raw";if(/<xrdMeasurements/.test(h)||/\.xrdml$/i.test(name))return"1.xrdml";if(h.startsWith(";RAW4.00")||h.includes("[RawHeader]"))return"7.txt";if(h.includes("[Scan points]"))return"3.csv";if(h.startsWith("SampleIdent")&&h.includes("Alpha1"))return"5.dat";if(/^(2_theta|angle)\s*,/i.test(h))return"4.csv";return /\.xy$/i.test(name)?"6.xy":"0.csv"}
function raw(bytes){let m=-1;for(let i=0;i<bytes.length-3;i++)if(bytes[i]===68&&bytes[i+1]===65&&bytes[i+2]===0&&bytes[i+3]===0){m=i;break}if(m<0)throw Error("Unsupported RAW binary layout.");const dv=new DataView(bytes.buffer,bytes.byteOffset,bytes.byteLength),n=dv.getUint32(m+16,true),start=m+20;if(n<2||start+n*4>bytes.length)throw Error("Invalid RAW data block.");return Array.from({length:n},(_,i)=>[i,dv.getFloat32(start+i*4,true)])}
function parse(name,text,bytes){const t=type(name,text,bytes);let p;if(t==="1.xrdml"){const xml=new DOMParser().parseFromString(text,"application/xml"),get=tag=>[...xml.getElementsByTagNameNS("*",tag)][0]?.textContent,pos=[...xml.getElementsByTagNameNS("*","positions")].find(e=>e.getAttribute("axis")==="2Theta"),start=+pos.getElementsByTagNameNS("*","startPosition")[0].textContent,end=+pos.getElementsByTagNameNS("*","endPosition")[0].textContent,y=numbers(get("counts"));p=y.map((v,i)=>[start+(end-start)*i/Math.max(y.length-1,1),v])}else if(t==="2.raw")p=raw(bytes);else if(t==="3.csv")p=pairs(text.split("[Scan points]")[1]||"",1);else if(t==="5.dat"){const lines=text.split(/\r?\n/),i=lines.findIndex(l=>{const v=numbers(l);return v.length>=3&&v[0]<v[2]&&v[1]<v[2]-v[0]}),h=numbers(lines[i]||"");if(i<0)throw Error("DAT scan range is missing.");const y=lines.slice(i+1).flatMap(numbers),[a,,b]=h;p=y.map((v,j)=>[a+(b-a)*j/Math.max(y.length-1,1),v])}else if(t==="7.txt")p=pairs(text.split("[Data]")[1]||"",2);else p=pairs(text);return{type:t,points:p}}
const f=n=>Number(n).toPrecision(10).replace(/\.?0+e/,"e").replace(/\.$/,"");
function output(p,fmt){const q=p.points,[a,b]=[q[0][0],q.at(-1)[0]],step=(b-a)/Math.max(q.length-1,1),rows=q.map(([x,y])=>`${f(x)},${f(y)}`);if(fmt==="0.csv")return rows.join("\n")+"\n";if(fmt==="4.csv")return"2_theta,Intensity\n"+rows.join("\n")+"\n";if(fmt==="6.xy")return q.map(([x,y])=>`${f(x)} ${f(y)}`).join("\n")+"\n";if(fmt==="3.csv")return`[Measurement conditions]\nScan range,${f(a)},${f(b)}\nScan step size,${f(step)}\nNo. of points,${q.length}\n[Scan points]\nAngle, TimePerStep, Intensity, ESD\n`+q.map(([x,y])=>`${f(x)}, 1, ${f(y)}, 0`).join("\n")+"\n";if(fmt==="5.dat")return`SampleIdent ____ DataFileName ______\nDiffrType ______   GeneratorVoltage __   TubeCurrent __\nAnode __    Alpha1  1.54060    Alpha2  1.54443    Ratio  0.50000\nMonochromatorUsed __   DivergenceSlit _      ReceivingSlit ___\n  ${f(a)}   ${f(step)}  ${f(b)}\n`+q.map(x=>f(x[1])).reduce((r,v,i)=>(i%10?r[r.length-1]+" "+v:r.concat(v)),[]).join("\n")+"\n";if(fmt==="7.txt")return`;RAW4.00\n[RawHeader]\nNumberOfRanges=1\n\n[RangeHeader]\nStart=${f(a)}\nIncrement=${f(step)}\nSteps=${q.length}\n\n[Data]\n     Angle,       PSD,\n`+q.map(([x,y])=>`${f(x)}, ${f(y)},`).join("\n")+"\n";return`<?xml version="1.0" encoding="UTF-8"?>\n<xrdMeasurements xmlns="http://www.xrdml.com/XRDMeasurement/2.2"><xrdMeasurement><scan><dataPoints><positions axis="2Theta" unit="deg"><startPosition>${f(a)}</startPosition><endPosition>${f(b)}</endPosition></positions><counts unit="counts">${q.map(x=>f(x[1])).join(" ")}</counts></dataPoints></scan></xrdMeasurement></xrdMeasurements>\n`}
function renderInput(){const rows=pattern.points.slice(0,25).map(([x,y])=>`<tr><td>${f(x)}</td><td>${f(y)}</td></tr>`).join("");$("input-body").innerHTML=rows;$("input-meta").textContent=`${pattern.points.length.toLocaleString()} points · first 25 shown`;$("input-preview").hidden=false}
function renderOutput(){if(!pattern)return;const data=output(pattern,format.value),lines=data.split("\n");$("output-body").textContent=lines.slice(0,30).join("\n")+(lines.length>30?"\n…":"");$("output-meta").textContent=`${format.value} · first ${Math.min(30,lines.length)} lines shown`;$("output-preview").hidden=false}
file.addEventListener("change",async()=>{selectedFile=file.files[0];if(!selectedFile)return;try{const bytes=new Uint8Array(await selectedFile.arrayBuffer()),text=new TextDecoder().decode(bytes);pattern=parse(selectedFile.name,text,bytes);status.textContent=`Detected ${pattern.type}: ${pattern.points.length.toLocaleString()} data points.`;button.disabled=false;renderInput();renderOutput()}catch(e){pattern=null;button.disabled=true;$("input-preview").hidden=true;$("output-preview").hidden=true;status.textContent=`Could not read file: ${e.message}`}});
format.addEventListener("change",renderOutput);
button.addEventListener("click",()=>{const fmt=format.value,blob=new Blob([output(pattern,fmt)],{type:"text/plain;charset=utf-8"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=selectedFile.name.replace(/\.[^.]+$/,"")+"_converted."+fmt.split(".").pop();a.click();recordConversion();status.textContent=`Conversion complete — ${conversionTotal().toLocaleString()} files converted so far.`;setTimeout(()=>URL.revokeObjectURL(a.href),0)});
